### ISSUE TITLE
Remove the responsiveness on the toolbar

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#193]
the main toolbar elements are too wide...maybe we can have the buttons shrink or remove the word preview and just have the eye infographic when the window narrows. 

the insert toolbar moves down for some reason and the canvas moves up

**Comment by MathuraMG** [comment]
I've seen this, I think it's time we adda  responsive design :) Keeping only the eye infographic and reducing the widths seems like a good idea. Shall we keep that as the final design?

**Comment by estherhersh** [comment]
teachers were confused by the infographic so we're changing some things....maybe the toolbar height can expand and create two rows and the buttons that are foating right can center....I'll play with it.

**Comment by MathuraMG** [comment]
Cool! Let me know the design and we can implement it :) Moving more things into a hamburger menu is also an option!

**Comment by MathuraMG** [comment]
Do we have a design on this? If yes, can we attach it here?
