### ISSUE TITLE
add to google classroom button

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#202]
https://developers.google.com/classroom/guides/sharebutton

**Comment by MathuraMG** [comment]
@estherhersh - Do you have the design for this?

**Comment by MathuraMG** [comment]
Using the client side method as share to classroom doesn't seem to be an option in nodeapis
https://github.com/google/google-api-nodejs-client
https://developers.google.com/apis-explorer/#p/

**Comment by estherhersh** [comment]
Noooooo . Does that package help?

**Comment by MathuraMG** [comment]
nah, the package doesn't work. But the link you sent works great! Im just finishing up on  styling!

**Comment by estherhersh** [comment]
oh yay!
