### ISSUE TITLE
Return 404 if unknown user name is entered in profile URL

### ISSUE THREAD

**Issue by MathuraMG** [peblio/app#320]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
@komalahuwalia would you able to pick this up?

**Comment by komalahuwalia** [comment]
The 502 was caused because we accessed user info without checking if the user info was null. This led to the server crashing returning a 502. A check to see if user retrieve returned a user was put in to solve this error

**Comment by MathuraMG** [comment]
fixed in #651
