### ISSUE TITLE
You can't use tab inside a text area 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#430]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
Focus leaves the draft-js component on tab. 
Need to look into the behaviour of the [onTab](https://jpuri.github.io/react-draft-wysiwyg/#/docs?_k=jjqinp) callback in wysiwyg-draft-js component

**Comment by MathuraMG** [comment]
Duplicate of #658
