### ISSUE TITLE
video component 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#436]
![group 2](https://user-images.githubusercontent.com/14132409/45227000-f24c0000-b28d-11e8-9f47-81588290ffd0.png)

- the toolbar should overlay the video and only display with edit mode on 
-the default site should be the following (https://peblio.github.io/instructions/video.html)
-the svg in the toolbar is. I'll send the svg on slack 
![group 8](https://user-images.githubusercontent.com/14132409/45227264-37703200-b28e-11e8-9134-350a08fa3b3d.png)

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
@estherhersh  - if we add a video component, do we need the changes in #437 ?

**Comment by estherhersh** [comment]
Yes. Not all iframes need back and forth
