### ISSUE TITLE
we'll have updated designs but for now the svgs should turn white when the file is selected

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#438]
<img width="1055" alt="screen shot 2018-09-07 at 11 36 27 am" src="https://user-images.githubusercontent.com/14132409/45228864-51ac0f00-b292-11e8-96f6-728a175afa66.png">

**Comment by MathuraMG** [comment]
Question - shouldn't the background be yellow for consistency with the blue for the folders?
<img width="828" alt="screen shot 2018-11-08 at 1 25 24 pm" src="https://user-images.githubusercontent.com/5505598/48185037-dc27f200-e359-11e8-9fb1-1f7a23e70abd.png">

**Comment by estherhersh** [comment]
@MathuraMG yeah that looks good let's go with that
