### ISSUE TITLE
Specify Node-Engine versions in package.json

### ISSUE THREAD

**Issue by designviacode** [peblio/app#439]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### Feature enhancement details:
specify in both `client` and `server` side, package.json fiiles the specific node-version we're using on our production server, so as to prevent any un-foreseen errors when deploying in production.

using the `engines` property in `package.json`.

**Comment by MathuraMG** [comment]
My system is currently on v8.7.0 of node. @komalahuwalia does it make sense to add this version in client and server?

**Comment by MathuraMG** [comment]
@komalahuwalia what do you think?
