### ISSUE TITLE
Giphs are freezing with edit mode off 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#443]
@MathuraMG @designviacode  is this happening for you too? 

![giphs freezing sm](https://user-images.githubusercontent.com/14132409/45436086-f27a4000-b67f-11e8-819f-d0d2b83d709f.gif)

**Comment by MathuraMG** [comment]
@estherhersh  - can you have a look?

**Comment by estherhersh** [comment]
looks fine to me now...

**Comment by MathuraMG** [comment]
Closing for now.
