### ISSUE TITLE
Image crop and rotate 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#454]
![group 40 2](https://user-images.githubusercontent.com/14132409/45650010-f4d30480-ba9a-11e8-91ee-2f026b1bf6e5.png)
![group 37 1](https://user-images.githubusercontent.com/14132409/45650011-f6043180-ba9a-11e8-98e5-365e2d3ca202.png)
![group 41 3](https://user-images.githubusercontent.com/14132409/45650014-f7355e80-ba9a-11e8-8d1d-2314ef874c87.png)
![group 40 1](https://user-images.githubusercontent.com/14132409/45650017-f8668b80-ba9a-11e8-86fd-fc020f82ab34.png)

**Comment by MathuraMG** [comment]
@estherhersh any chance you remember which library we had in mind for this?
