### ISSUE TITLE
Codepen embeds don't work 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#465]
Here is a sample iframe from them 
<iframe height='308' scrolling='no' title='rgb color sliders' src='//codepen.io/leemark/embed/lpEHr/?height=308&theme-id=0&default-tab=result&embed-version=2' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'>See the Pen <a href='https://codepen.io/leemark/pen/lpEHr/'>rgb color sliders</a> by Mark Lee (<a href='https://codepen.io/leemark'>@leemark</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
Works here -> https://demo.peblio.co/pebl/gK3egFF-3
