### ISSUE TITLE
Rollover text 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#484]
Add descriptions to buttons when you hover 

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
@estherhersh - silly request, can you list all the buttons here? So I dont miss any?

**Comment by estherhersh** [comment]
Table of contents: 
1. Refresh
2. Close 

Closed Table of contents icon:
1. Table of contents 

Components:
1. Duplicate 
2. Drag and Drop 
3. Delete 

Main Toolbar:
1. Settings 
2. Account
3. Page Title 

Editor:
1. Run Code
2. Stop Code 
3. Toggle Console

**Comment by MathuraMG** [comment]
reopening because it had to be reverted due to #523
