### ISSUE TITLE
when you hover over a text box the cursor freaks out between an arrow and a text cursor

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#488]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
@estherhersh  - is this still an issue?

**Comment by MathuraMG** [comment]
Closing for now.
