### ISSUE TITLE
Heading sizes don't stay consistent in the text boxes

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#505]
If you change "normal" to H1 in middle of a text box, it doesn't match the h1 font size. 

![inconsistentsizes](https://user-images.githubusercontent.com/14132409/47863452-afaa2e00-ddcd-11e8-8297-dc2143877c08.gif)

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
@estherhersh - I am unable to reproduce this.. can you help me out?

**Comment by estherhersh** [comment]
Sample page https://demo.peblio.co/pebl/yLtrSXW1V

**Comment by MathuraMG** [comment]
Unable to replicate. Making the issue inactive for now

**Comment by MathuraMG** [comment]
This issue requires us to add an additional level of css to force the heading sizes to stay consistent. If I am not mistaken, this is a quick fix. Will look to finishing this.
