### ISSUE TITLE
Introduce tags in the DB models

### ISSUE THREAD

**Issue by MathuraMG** [peblio/app#566]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by komalahuwalia** [comment]
Add  a Tag model which has 2 attributes:
1. TagName
2. TimeStamp

The TimeStamp is just for future requirements.

**Comment by MathuraMG** [comment]
fixed in #589
