### ISSUE TITLE
Add API to retrieve pages by tag

### ISSUE THREAD

**Issue by MathuraMG** [peblio/app#567]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by komalahuwalia** [comment]
1. Add api to add Tag
/api/tag POST
2. Add api to retrieve all Tags
/api/tag GET
3. Add api to retrieve tag that starts with 
eg: /api/tag?startsWith="Jav" GET
4. Add Patch api on Pages to add Tags to a Page
Page shall have an array of Tag
The patch api will take all tags and update the page with those tags
5. Add Get api on Pages that can find Pages given a tag

Tags can have spaces

**Comment by MathuraMG** [comment]
Completed in #594 .
Will close after pagnation is complete.

**Comment by MathuraMG** [comment]
completed in #603
