### ISSUE TITLE
Add indexing for elastic search of tags

### ISSUE THREAD

**Issue by MathuraMG** [peblio/app#572]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
@komalahuwalia  - can i close this?

**Comment by komalahuwalia** [comment]
We did not really end up indexing our tags, but our search on tags is quite fast at this point. SO for now we can close it. May be later we can revisit if with more data, is our search slowing down
