### ISSUE TITLE
Add file sorting options in the file modal

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#591]
Sort files by title (alphabetically), by date created, or by date modified by clicking on the column headings in the file> open modal. 
It seems to be sorted by "last modified" in the profile pages but I would sort it alphabetically so that people can name lessons "lesson 01, lesson 02 etc..." and have them in the right order in their profiles. 

<img width="857" alt="screen shot 2019-01-15 at 12 48 53 pm" src="https://user-images.githubusercontent.com/14132409/51199116-f33c1080-18c3-11e9-8bb9-a11e66fda394.png">

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
@estherhersh I just want to confirm 2 things -
1. Will the default sort still be updatedAt ?
2. I assume that it will always be the default sort and the user will have to sort alphabetically/ createdBy as they see fit?

**Comment by estherhersh** [comment]
the files in the modal should be sorted by date updated by default and ideally changed when you click on the column headings. But in the profile pages, they should be sorted alphabetically by default because we have folders with lesson plans all out of order because they were updated at different times.

**Comment by MathuraMG** [comment]
fixed in #657
