### ISSUE TITLE
add description 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#599]
This is just for the teacher side. The student side will have the same user flow but will say "share" and lead to the same modal with a "share" button instead of "save." I'm creating a separate issue for that. 
This button should dissapear with edit mode off along with the tag input. 

<img width="586" alt="screen shot 2019-01-24 at 8 15 44 am" src="https://user-images.githubusercontent.com/14132409/51689359-c10d6b80-1fb3-11e9-8179-dda271ba46fa.png">
<img width="292" alt="screen shot 2019-01-24 at 8 16 16 am" src="https://user-images.githubusercontent.com/14132409/51689362-c2d72f00-1fb3-11e9-8066-ba4771537c89.png">

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
@estherhersh  I have some question around the add description design. We can see it on the main pebl as well right? If yes, why do we need an additional modal to put it in? Can it be like the title where there is an are for it and you add it?

And for the students, can we just add a "share option" (which is like a toggle?)

**Comment by MathuraMG** [comment]
fixed in #604
