### ISSUE TITLE
Add usernames for everyone

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#643]
For student privacy 

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
@estherhersh @komalahuwalia I think we need to discuss how this will work for current users..
@estherhersh - are we doing this for privacy concerns?
