### ISSUE TITLE
Design QA

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#679]
- [x] Add a bit of padding to the add description button 

- [x] The edit page title icon is outside of the input and looks like a button but isn't...clicking on it should activate the input and the icon should be inside the input 

- [x] The video icon doesn't highlight 
<img width="50" alt="Screen Shot 2019-05-28 at 6 13 13 PM" src="https://user-images.githubusercontent.com/14132409/58515897-47a9a380-8174-11e9-8964-9e498eeadb68.png">

- [ ] Automatically remove the table of contents when the page is too narrow and center the canvas

- [x] remove background from editor settings button and fix color
![17214](https://user-images.githubusercontent.com/14132409/58515581-53489a80-8173-11e9-8287-08b840d95460.png)
<img width="53" alt="Screen Shot 2019-05-28 at 6 06 09 PM" src="https://user-images.githubusercontent.com/14132409/58515592-593e7b80-8173-11e9-8186-19b376ce2578.png">

- [ ] COMMUNITY WEBSITE: use svg for logo for  so that it's not pixelated (export from figma)

- [x] the link buttons are not visible without hover 
<img width="271" alt="Screen Shot 2019-05-28 at 6 07 37 PM" src="https://user-images.githubusercontent.com/14132409/58515653-87bc5680-8173-11e9-85da-79495f139782.png">

- [x] the added files don't shrink when it gets past the size of the editor
<img width="1048" alt="Screen Shot 2019-05-28 at 6 10 18 PM" src="https://user-images.githubusercontent.com/14132409/58515778-f39ebf00-8173-11e9-84e8-c386fa3b1b0b.png">

- [x] There's a small gap between toolbars and you can see the page behind it as you scroll 
<img width="983" alt="Screen Shot 2019-05-28 at 6 12 00 PM" src="https://user-images.githubusercontent.com/14132409/58515855-2a74d500-8174-11e9-9679-96c01b0a8fb0.png">

- [x] the tag on the editors with the language name should always be 57px wide with an increase border radius (unless the word is too long.) The buttons should be right next to it 
<img width="31" alt="Screen Shot 2019-05-28 at 6 32 15 PM" src="https://user-images.githubusercontent.com/14132409/58516816-4fb71280-8177-11e9-9c7e-fa056e9d6125.png">
<img width="75" alt="Screen Shot 2019-05-28 at 6 34 13 PM" src="https://user-images.githubusercontent.com/14132409/58516819-5180d600-8177-11e9-969a-96776ff6ee9a.png">

- [x] the bullets don’t indent on pages. The bullet changes style but stays completely left aligned 

- [ ] can we move everything over to allow for more space to show the full title? 
<img width="1282" alt="Screen Shot 2019-07-10 at 8 56 13 AM" src="https://user-images.githubusercontent.com/14132409/60984475-a2482a80-a2f0-11e9-94f7-b7995caa260e.png">

**Comment by estherhersh** [comment]
@MathuraMG added a bit to these

**Comment by MathuraMG** [comment]
@komalahuwalia you mind if I do the below issue? I'm adding something else to the toolbar as we speak, and it looks weird if I dont fix this.
- [ ] remove background from editor settings button and fix color
![17214](https://user-images.githubusercontent.com/14132409/58515581-53489a80-8173-11e9-8287-08b840d95460.png)
<img width="53" alt="Screen Shot 2019-05-28 at 6 06 09 PM" src="https://user-images.githubusercontent.com/14132409/58515592-593e7b80-8173-11e9-8186-19b376ce2578.png">

**Comment by MathuraMG** [comment]
Closing this issues. The rest is being fixed as part of #749
