### ISSUE TITLE
Pressing save messes up the UI 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#687]
![save bugg](https://user-images.githubusercontent.com/14132409/57542485-d2d70c80-731f-11e9-8916-c5105b25cb7f.gif)

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
fixed in #690
