### ISSUE TITLE
file structure new design 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#709]
![Group 51](https://user-images.githubusercontent.com/14132409/58554954-4f099500-81e6-11e9-845a-e0283956b440.png)
![Group 48 (1)](https://user-images.githubusercontent.com/14132409/58554955-503ac200-81e6-11e9-99f7-0905cd0e72df.png)

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
fixed in #755
