### ISSUE TITLE
css issue list 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#736]
- [x] only sometimes, the icon to minimize the full screen editor is cut off. (try the second editor on the page)
<img width="44" alt="Screen Shot 2019-06-19 at 10 19 01 AM" src="https://user-images.githubusercontent.com/14132409/59773628-f0cb5180-927b-11e9-9d98-adb29414503c.png">

- [x] weird gray box at the bottom of dashboard pages 
<img width="853" alt="Screen Shot 2019-06-17 at 7 18 34 PM" src="https://user-images.githubusercontent.com/14132409/59773659-fc1e7d00-927b-11e9-9d22-3a0178e9b184.png">

- [x] The folders are not in alphabetical order 
<img width="1010" alt="Screen Shot 2019-06-19 at 10 22 54 AM" src="https://user-images.githubusercontent.com/14132409/59773790-40aa1880-927c-11e9-9868-8bb7d7a78b9c.png">

- [x] The background of the icon circle should be white 
<img width="213" alt="Screen Shot 2019-06-19 at 10 23 50 AM" src="https://user-images.githubusercontent.com/14132409/59773852-58819c80-927c-11e9-93e6-4885387702ca.png">

- [x] Align breadcrumbs with title 
<img width="104" alt="Screen Shot 2019-06-19 at 10 24 29 AM" src="https://user-images.githubusercontent.com/14132409/59773930-7f3fd300-927c-11e9-8241-a4f4fa146afa.png">

- [x] I think we should flip that last arrow downward
<img width="373" alt="Screen Shot 2019-06-19 at 10 26 16 AM" src="https://user-images.githubusercontent.com/14132409/59774028-b8784300-927c-11e9-9ad2-b317626cb6d3.png">

- [x] Add new button on dashboard is messed up 
<img width="103" alt="Screen Shot 2019-06-19 at 12 35 27 PM" src="https://user-images.githubusercontent.com/14132409/59783731-cf279580-928e-11e9-8ba4-c072e5d7a8bd.png">

- [x] the bullets are not indenting 
<img width="239" alt="Screen Shot 2019-06-19 at 2 47 56 PM" src="https://user-images.githubusercontent.com/14132409/59792043-554cd780-92a1-11e9-8684-2bfe0132d708.png">

- [x] The forgot password turns white on hover and covers the button 
<img width="474" alt="Screen Shot 2019-06-19 at 1 53 55 PM" src="https://user-images.githubusercontent.com/14132409/59792065-61d13000-92a1-11e9-95b5-e14107c2783f.png">

**Comment by MathuraMG** [comment]
Additional Issues - 
[ ] Too many variations of $blue
