### ISSUE TITLE
History 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#737]
![Group 2 (7)](https://user-images.githubusercontent.com/14132409/59922449-cc4bb280-93fe-11e9-9956-551ff02e04c9.png)
<img width="1440" alt="Group 37 1" src="https://user-images.githubusercontent.com/14132409/59922454-ce157600-93fe-11e9-9812-d93fbbd629f6.png">
![Group 2 (8)](https://user-images.githubusercontent.com/14132409/59922457-cf46a300-93fe-11e9-92fa-3663cd17d13d.png)

**Comment by MathuraMG** [comment]
fixed in #741
