### ISSUE TITLE
Return 404 for PageVersion if the page is trashed or deleted. 

### ISSUE THREAD

**Issue by komalahuwalia** [peblio/app#754]
Check while retrieving Page Version if Page is trashed or deleted. 
Return 404 for PageVersion if the page is trashed or deleted. 

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment]
fixed in #796
