### ISSUE TITLE
Fix Google Sign Integration in for Peblio

### ISSUE THREAD

**Issue by komalahuwalia** [peblio/app#889]
This are several issues related to google sign in and signup.

1. Add catch blocks to every sign in action so that if anything fails, we show user some message
2. Add appropriate messages for all google sign in and login failures
3. Intermettingtly this error is seen:
Uncaught TypeError: Cannot read property 'signIn' of undefined

**Comment by komalahuwalia** [comment]
Issue no 1 and 2 have been fixed by https://github.com/peblio/app/pull/894
Issue 3 is only partially fixed since we were not able to find out why the auth2 errors out on second init onwards.
For now we have only added a if check. In case the auth2 object does not exist, we show an error isntead of failing to log in

**Comment by MathuraMG** [comment]
WIll not fix issue 3
